//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 12:50:21 PM CET 
//


package com.blame.gsv.jaxbgenerated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.blame.gsv.jaxbgenerated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.blame.gsv.jaxbgenerated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Panorama }
     * 
     */
    public Panorama createPanorama() {
        return new Panorama();
    }

    /**
     * Create an instance of {@link Panorama.AnnotationProperties }
     * 
     */
    public Panorama.AnnotationProperties createPanoramaAnnotationProperties() {
        return new Panorama.AnnotationProperties();
    }

    /**
     * Create an instance of {@link Panorama.DataProperties }
     * 
     */
    public Panorama.DataProperties createPanoramaDataProperties() {
        return new Panorama.DataProperties();
    }

    /**
     * Create an instance of {@link Panorama.ProjectionProperties }
     * 
     */
    public Panorama.ProjectionProperties createPanoramaProjectionProperties() {
        return new Panorama.ProjectionProperties();
    }

    /**
     * Create an instance of {@link Panorama.AnnotationProperties.Link }
     * 
     */
    public Panorama.AnnotationProperties.Link createPanoramaAnnotationPropertiesLink() {
        return new Panorama.AnnotationProperties.Link();
    }

}
