//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 12:50:21 PM CET 
//


package com.blame.gsv.jaxbgenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data_properties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="street_range" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="image_width" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="image_height" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="tile_width" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="tile_height" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="image_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pano_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="imagery_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num_zoom_levels" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="lng" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="original_lat" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="original_lng" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="elevation_wgs84_m" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="elevation_egm96_m" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="projection_properties">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="projection_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pano_yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="tilt_yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="tilt_pitch_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="annotation_properties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="link" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="link_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="pano_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="road_argb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataProperties",
    "projectionProperties",
    "annotationProperties"
})
@XmlRootElement(name = "panorama")
public class Panorama {

    @XmlElement(name = "data_properties", required = true)
    protected Panorama.DataProperties dataProperties;
    @XmlElement(name = "projection_properties", required = true)
    protected Panorama.ProjectionProperties projectionProperties;
    @XmlElement(name = "annotation_properties", required = true)
    protected Panorama.AnnotationProperties annotationProperties;

    /**
     * Gets the value of the dataProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Panorama.DataProperties }
     *     
     */
    public Panorama.DataProperties getDataProperties() {
        return dataProperties;
    }

    /**
     * Sets the value of the dataProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Panorama.DataProperties }
     *     
     */
    public void setDataProperties(Panorama.DataProperties value) {
        this.dataProperties = value;
    }

    /**
     * Gets the value of the projectionProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Panorama.ProjectionProperties }
     *     
     */
    public Panorama.ProjectionProperties getProjectionProperties() {
        return projectionProperties;
    }

    /**
     * Sets the value of the projectionProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Panorama.ProjectionProperties }
     *     
     */
    public void setProjectionProperties(Panorama.ProjectionProperties value) {
        this.projectionProperties = value;
    }

    /**
     * Gets the value of the annotationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Panorama.AnnotationProperties }
     *     
     */
    public Panorama.AnnotationProperties getAnnotationProperties() {
        return annotationProperties;
    }

    /**
     * Sets the value of the annotationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Panorama.AnnotationProperties }
     *     
     */
    public void setAnnotationProperties(Panorama.AnnotationProperties value) {
        this.annotationProperties = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="link" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="link_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="pano_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="road_argb" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class AnnotationProperties {

        protected List<Panorama.AnnotationProperties.Link> link;

        /**
         * Gets the value of the link property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the link property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Panorama.AnnotationProperties.Link }
         * 
         * 
         */
        public List<Panorama.AnnotationProperties.Link> getLink() {
            if (link == null) {
                link = new ArrayList<Panorama.AnnotationProperties.Link>();
            }
            return this.link;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="link_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="pano_id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="road_argb" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "linkText"
        })
        public static class Link {

            @XmlElement(name = "link_text", required = true)
            protected String linkText;
            @XmlAttribute(name = "yaw_deg")
            protected Float yawDeg;
            @XmlAttribute(name = "pano_id")
            protected String panoId;
            @XmlAttribute(name = "road_argb")
            protected String roadArgb;

            /**
             * Gets the value of the linkText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLinkText() {
                return linkText;
            }

            /**
             * Sets the value of the linkText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLinkText(String value) {
                this.linkText = value;
            }

            /**
             * Gets the value of the yawDeg property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getYawDeg() {
                return yawDeg;
            }

            /**
             * Sets the value of the yawDeg property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setYawDeg(Float value) {
                this.yawDeg = value;
            }

            /**
             * Gets the value of the panoId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPanoId() {
                return panoId;
            }

            /**
             * Sets the value of the panoId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPanoId(String value) {
                this.panoId = value;
            }

            /**
             * Gets the value of the roadArgb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRoadArgb() {
                return roadArgb;
            }

            /**
             * Sets the value of the roadArgb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRoadArgb(String value) {
                this.roadArgb = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="street_range" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="image_width" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="image_height" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="tile_width" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="tile_height" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="image_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pano_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="imagery_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num_zoom_levels" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="lng" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="original_lat" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="original_lng" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="elevation_wgs84_m" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="elevation_egm96_m" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "copyright",
        "text",
        "streetRange",
        "region",
        "country"
    })
    public static class DataProperties {

        @XmlElement(required = true)
        protected String copyright;
        @XmlElement(required = true)
        protected String text;
        @XmlElement(name = "street_range")
        protected byte streetRange;
        @XmlElement(required = true)
        protected String region;
        @XmlElement(required = true)
        protected String country;
        @XmlAttribute(name = "image_width")
        protected Short imageWidth;
        @XmlAttribute(name = "image_height")
        protected Short imageHeight;
        @XmlAttribute(name = "tile_width")
        protected Short tileWidth;
        @XmlAttribute(name = "tile_height")
        protected Short tileHeight;
        @XmlAttribute(name = "image_date")
        protected String imageDate;
        @XmlAttribute(name = "pano_id")
        protected String panoId;
        @XmlAttribute(name = "imagery_type")
        protected String imageryType;
        @XmlAttribute(name = "num_zoom_levels")
        protected Short numZoomLevels;
        @XmlAttribute(name = "lat")
        protected Float lat;
        @XmlAttribute(name = "lng")
        protected Float lng;
        @XmlAttribute(name = "original_lat")
        protected Float originalLat;
        @XmlAttribute(name = "original_lng")
        protected Float originalLng;
        @XmlAttribute(name = "elevation_wgs84_m")
        protected Float elevationWgs84M;
        @XmlAttribute(name = "elevation_egm96_m")
        protected Float elevationEgm96M;

        /**
         * Gets the value of the copyright property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCopyright() {
            return copyright;
        }

        /**
         * Sets the value of the copyright property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCopyright(String value) {
            this.copyright = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the streetRange property.
         * 
         */
        public byte getStreetRange() {
            return streetRange;
        }

        /**
         * Sets the value of the streetRange property.
         * 
         */
        public void setStreetRange(byte value) {
            this.streetRange = value;
        }

        /**
         * Gets the value of the region property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegion() {
            return region;
        }

        /**
         * Sets the value of the region property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegion(String value) {
            this.region = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the imageWidth property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getImageWidth() {
            return imageWidth;
        }

        /**
         * Sets the value of the imageWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setImageWidth(Short value) {
            this.imageWidth = value;
        }

        /**
         * Gets the value of the imageHeight property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getImageHeight() {
            return imageHeight;
        }

        /**
         * Sets the value of the imageHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setImageHeight(Short value) {
            this.imageHeight = value;
        }

        /**
         * Gets the value of the tileWidth property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getTileWidth() {
            return tileWidth;
        }

        /**
         * Sets the value of the tileWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setTileWidth(Short value) {
            this.tileWidth = value;
        }

        /**
         * Gets the value of the tileHeight property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getTileHeight() {
            return tileHeight;
        }

        /**
         * Sets the value of the tileHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setTileHeight(Short value) {
            this.tileHeight = value;
        }

        /**
         * Gets the value of the imageDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageDate() {
            return imageDate;
        }

        /**
         * Sets the value of the imageDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageDate(String value) {
            this.imageDate = value;
        }

        /**
         * Gets the value of the panoId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPanoId() {
            return panoId;
        }

        /**
         * Sets the value of the panoId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPanoId(String value) {
            this.panoId = value;
        }

        /**
         * Gets the value of the imageryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageryType() {
            return imageryType;
        }

        /**
         * Sets the value of the imageryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageryType(String value) {
            this.imageryType = value;
        }

        /**
         * Gets the value of the numZoomLevels property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getNumZoomLevels() {
            return numZoomLevels;
        }

        /**
         * Sets the value of the numZoomLevels property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setNumZoomLevels(Short value) {
            this.numZoomLevels = value;
        }

        /**
         * Gets the value of the lat property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLat(Float value) {
            this.lat = value;
        }

        /**
         * Gets the value of the lng property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLng() {
            return lng;
        }

        /**
         * Sets the value of the lng property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLng(Float value) {
            this.lng = value;
        }

        /**
         * Gets the value of the originalLat property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getOriginalLat() {
            return originalLat;
        }

        /**
         * Sets the value of the originalLat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setOriginalLat(Float value) {
            this.originalLat = value;
        }

        /**
         * Gets the value of the originalLng property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getOriginalLng() {
            return originalLng;
        }

        /**
         * Sets the value of the originalLng property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setOriginalLng(Float value) {
            this.originalLng = value;
        }

        /**
         * Gets the value of the elevationWgs84M property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getElevationWgs84M() {
            return elevationWgs84M;
        }

        /**
         * Sets the value of the elevationWgs84M property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setElevationWgs84M(Float value) {
            this.elevationWgs84M = value;
        }

        /**
         * Gets the value of the elevationEgm96M property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getElevationEgm96M() {
            return elevationEgm96M;
        }

        /**
         * Sets the value of the elevationEgm96M property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setElevationEgm96M(Float value) {
            this.elevationEgm96M = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="projection_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pano_yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="tilt_yaw_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="tilt_pitch_deg" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ProjectionProperties {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "projection_type")
        protected String projectionType;
        @XmlAttribute(name = "pano_yaw_deg")
        protected Float panoYawDeg;
        @XmlAttribute(name = "tilt_yaw_deg")
        protected Float tiltYawDeg;
        @XmlAttribute(name = "tilt_pitch_deg")
        protected Float tiltPitchDeg;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the projectionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProjectionType() {
            return projectionType;
        }

        /**
         * Sets the value of the projectionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProjectionType(String value) {
            this.projectionType = value;
        }

        /**
         * Gets the value of the panoYawDeg property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getPanoYawDeg() {
            return panoYawDeg;
        }

        /**
         * Sets the value of the panoYawDeg property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setPanoYawDeg(Float value) {
            this.panoYawDeg = value;
        }

        /**
         * Gets the value of the tiltYawDeg property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getTiltYawDeg() {
            return tiltYawDeg;
        }

        /**
         * Sets the value of the tiltYawDeg property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setTiltYawDeg(Float value) {
            this.tiltYawDeg = value;
        }

        /**
         * Gets the value of the tiltPitchDeg property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getTiltPitchDeg() {
            return tiltPitchDeg;
        }

        /**
         * Sets the value of the tiltPitchDeg property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setTiltPitchDeg(Float value) {
            this.tiltPitchDeg = value;
        }

    }

}
